plugins/fields/Boolean/Index.tsx
=> fix: boolean field misaligned

features/api/middleware.ts
We need to figure out which user had issues with the app. We're going to log the user id and datasource id. No sensitive data.
Manual. 
Throw an error in an API route and see the result on sentry
=> chore: capture user info on crash

.dockerignore, package.json, scripts/docker-start.mjs
This PR adds a docker start script.
Manual test
=> [BST-200] chore: add docker start script

next.config.js
=> fix: redirect login register

.github/workflows/docker-publish.yml, Dockerfile, next.config.js
Tweak the actions workflow
Manual and GA
=> [BST-200] chore: use GitHub Actions to automatically build and deploy docker image

features/tables/components/RecordsTable.tsx
This was happening on the index page
=> fix: get records query was being made twice

pages/api/data-sources/[dataSourceId]/tables/[tableName]/records.ts, pages/api/records.ts
This happened because when we moved `records.ts`.
=> add the create route back

hooks/index.ts
This fixes a build error that's popping in our sentry. `document not defined`. We traced it to the responsive utilities.
=> fix: document not defined on build

features/code/evaluator.ts
It would crash the app if errors came up.
=> refactor: catch evaluator errors

.env.sample, components/ProductionScripts.tsx, pages/_app.tsx
This PR adds fullstory integration.
manual
=> chore: add fullstory integration

components/Shimmer.tsx, components/ShimmerOrCount.tsx, components/Sidebar.tsx, pages/data-sources/[dataSourceId].tsx, pages/views/[viewId].tsx
Minor visual tweaks to make it clear to the owner that the user can't see the tables and tiny additions to the datasource home page.
Manual
=> chore: minor visual tweaks

.github/workflows/docker-publish.yml, .github/workflows/refresh-proxy.yml
=> chore: fix actions files

.github/workflows/docker-publish.yml, features/cache/index.ts, features/options/index.ts, lib/constants.ts, plugins/data-sources/serverHelpers.ts
Add a redis toggle for running in a proxy
Manual
=> refactor: add redis option for runInProxy

features/api/middleware.ts
This fixes a memory leak that compounds times on top.
Manual
=> fix;l middleware memory leak

features/records/index.ts, plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts, plugins/fields/Association/Index.tsx
=> [BST-234] fix: association wrongly sends view ID

package.json, plugins/data-sources/ConnectionPooler.ts, yarn.lock
Add connection count in pm2 monitor [here](https://app.pm2.io/bucket/6196716500cc2c2d24fec6cc/backend/overview/servers).
This 👇
=> chore: pm2 connection count

pages/views/new.tsx
There was a failed request being done.
=> [BST-245] fix: failed request on load

features/data-sources/hooks.ts, features/records/components/RecordsIndexPage.tsx, features/records/components/ShowRecord.tsx, features/views/components/ViewEditDataSourceInfo.tsx, features/views/components/ViewEditFilters.tsx, features/views/components/ViewEditName.tsx, features/views/components/ViewEditVisibility.tsx, features/views/hooks.ts, hooks/index.ts, pages/views/[viewId].tsx, pages/views/[viewId]/edit.tsx
Minor quality of life hook `useViewResponse(viewId: string)`
=> refactor: userViewResponse hook

components/DataSourcesSidebar.tsx
Minor tweak to have less jitter on load.
=> refactor: always show DS sidebar

pages/api/views/[viewId]/columns.ts
`views.columns` was treated as an object instead of an array.
=> [BST-254] fix: virtual fields creation broken

Dockerfile
=> fix: broken docker image

pages/api/data-sources/check-connection.ts
=> fix: trim whitespaces in data source connection strings

.github/workflows/docker-publish.yml, Dockerfile
The docker build process is broken.
=> fix: broken docker build process

.env.sample, components/AnalyticsScripts.tsx, deploy/docker/.env.sample, deploy/docker/docker-compose.yml
This updates the configuration files for docker deployment.
=> refactor: env variables for docker

package.json, yarn.lock
Added production dependency `sharp`.
=> chore: add sharp

features/organizations/components/OrganizationsBlock.tsx, hooks/index.ts, pages/profile.tsx
This removes the role from the profile page and adds iy to the org block. The PR is mostly to test the automatic deployment feature.
=> chore: remove role from profile page

deploy/docker/docker-compose.yml
The docker compose config is broken
=> fix: docker-compose image broken

pages/views/[viewId].tsx, pages/views/[viewId]/edit.tsx
=> fix: add filters

package.json, yarn.lock
=> chore: update chakra-ui

plugins/fields/Json/Edit.tsx
JSON field was broken. I added the ability to edit with react-json-viewer.
=> [BST-268] fix: JSON field broken

features/records/components/EditRecord.tsx, features/records/components/NewRecord.tsx
=> [BST-271] fix: pretty 404 error message on edit

lib/constants.ts, pages/auth/register.tsx, pages/index.tsx
tool.new takes a user to the creation flow
=> chore: tool.new takes a user to the creation flow

components/OrganizationSidebar.tsx, components/PageWrapper.tsx, components/Sidebar.tsx
Sidebar had this overflow issue.
=> fix: sidebar overflow broken

pages/api/auth/register.ts, pages/auth/register.tsx
There was a bug in the register form with input fields getting unfocused.
=> fix: register fields get unfocused

pages/api/data-sources/[dataSourceId]/tables/[tableName]/records/[recordId].ts
=> [BST-275] fix: before value undefined

features/tables/components/RecordsTable.tsx, features/views/components/FieldEditor.tsx
Some columns were visible after the user disconnected them
=> [BST-276] fix: columns visible after disconnection

features/records/components/Form.tsx
Some hidden fields hide validation error messages.
=> [BST-274] fix: hidden error messages

plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
We're now finding the first column and counting that one.
=> [BST-281] fix: counting for * is a performance issue

plugins/data-sources/ConnectionPooler.ts
Sometimes queries get aborted because they get destroyed in the `ConnectionPooler`
=> [BST-278] fix: aborted queries

pages/api/views/[viewId]/columns/[columnName].ts
The issue was that the delete method treats the field as an object rather than an array.
=> [BST-280] fix: deleting columns breaks view

features/fields/components/FieldWrapper/EditFieldWrapper.tsx, plugins/fields/Association/Edit.tsx, plugins/fields/DateTime/Edit.tsx, plugins/fields/Id/Edit.tsx, plugins/fields/Number/Edit.tsx, plugins/fields/ProgressBar/Edit.tsx, plugins/fields/Select/Edit.tsx, plugins/fields/Text/Edit.tsx, plugins/fields/Textarea/Edit.tsx
The edit page fields weren't looking too good compared to the show page.
=> chore: edit page improvements

features/fields/hooks.ts, features/tables/components/RecordsTable.tsx, features/tables/hooks.ts, features/tables/types.d.ts, features/views/components/GenericSelectOption.tsx, plugins/fields/LinkTo/Inspector.tsx
Changed the type of the field from text inputs to drop-downs for a better experience.
=> refactor: drop-downs in has many

plugins/fields/Text/Index.tsx, plugins/fields/Text/Inspector.tsx, plugins/fields/Text/fieldOptions.ts, plugins/fields/Text/types.d.ts
Users might want to add `https://` to their link fields.
=> refactor: add prefix to link fields

features/dashboards/components/GenericCodeOption.tsx, features/dashboards/components/WidgetEditor.tsx, features/fields/components/FieldWrapper/IndexFieldWrapper.tsx, features/views/components/FieldEditor.tsx, features/views/components/GenericCodeOption.tsx, features/views/components/ViewEditColumns.tsx, package.json, yarn.lock
This adds a much needed code editor to the app.
=> feature: code editor

components/PageWrapper.tsx, features/data-sources/components/DataSourcesBlock.tsx, features/organizations/components/OrganizationsBlock.tsx, pages/profile.tsx
When you have multiple data sources and organizations it difficult to figure out which is which.
=> feature: group data sources by organization

next.config.js, package.json, yarn.lock
Reverting a previously hotfixed issue.
=> chore: sentry hotfix revert
